name: chat_online_flutter
description: Um app de chat com Flutter, Firebase e OneSignal

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  bubble: ^1.2.1
  cloud_firestore: ^2.5.4
  firebase_core: ^1.7.0
  get: ^4.3.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0


flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
